name: Ports
main: net.robinjam.bukkit.ports.Ports
version: ${project.version}
author: robinjam
depend: [WorldEdit]

commands:
  ports:
    description: Provides access to Ports commands
    usage: /<command>

permissions:
  ports.*:
    description: Gives access to all Ports features
    default: op
    children:
      ports.reload: true
      
  ports.reload:
    description: Allows you to use /ports reload