name: Ports
main: net.robinjam.bukkit.ports.Ports
version: ${project.version}
author: robinjam
depend: [WorldEdit]
database: true

commands:
  port:
    description: Provides access to Ports commands
    usage: /<command>

permissions:
  ports.*:
    description: Gives access to all Ports features
    default: op
    children:
      ports.reload: true
      ports.create: true
      ports.delete: true
      ports.select: true
      ports.arrive: true
      ports.update: true
      ports.dispatch: true
      ports.describe: true
      ports.destination: true
      
  ports.reload:
    description: Allows you to use /port reload
  
  ports.create:
    description: Allows you to use /port create
  
  ports.delete:
    description: Allows you to use /port delete
  
  ports.select:
    description: Allows you to use /port select
  
  ports.arrive:
    description: Allows you to use /port arrive
  
  ports.update:
    description: Allows you to use /port update
  
  ports.dispatch:
    description: Allows you to use /port dispatch
  
  ports.describe:
    description: Allows you to use /port describe
  
  ports.destination:
    description: Allows you to use /port destination
  
  ports.list:
    description: Allows you to use /port list
    default: true