name: Ports
main: net.robinjam.bukkit.ports.Ports
version: ${project.version}
author: robinjam
depend: [WorldEdit]
database: true

commands:
  port:
    description: Provides access to Ports commands
    usage: /<command>

permissions:
  ports.*:
    description: Gives access to all Ports features
    default: op
    children:
      ports.reload: true
      ports.create: true
      ports.delete: true
      
  ports.reload:
    description: Allows you to use /port reload
  
  ports.create:
    description: Allows you to use /port create
  
  ports.delete:
    description: Allows you to use /port delete
  
  ports.list:
    description: Allows you to use /port list
    default: true